# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: push nuget

on:
  push:
    branches: [ "wip" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: ./.github/gitversion.yml
    - name: Show version
      run: |
        echo "version: ${{ steps.gitversion.outputs.AssemblySemVer }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package nuget
      run: dotnet pack ProstoA.Core.sln --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.FullSemVer }} #AssemblySemVer }} --version-suffix ${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./package/*.nupkg --source https://nuget.pkg.github.com/ProstoA/index.json --api-key ${{ secrets.MY_TOKEN }}
